### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-kotlin#18]
### Problem

It would be great to be able to generate library docs.

### Description

I might have a working solution on [this branch](https://github.com/thunderbiscuit/bdk-kotlin/tree/auto-generated-docs) of my repo.

The workflow is as follows:
1. create a fresh bindings file
2. apply the patch `docs.patch` using `patch jvm/src/main/kotlin/org/bitcoindevkit/bdk.kt docs.patch`
3. generate the website using `./gradlew :jvm:dokkaHtml`

The main question I have and the reason I have not put too much time in trying to port over all of the docs and polishing the current branch is that the patch does not seem to apply that easily, and I don't know to which extent the addition of a new API changes the bindings file. If the changes are extensive, I assume the patch will not work, and I'm still looking at a good way to fix that (like some interactive way using a GUI maybe), because at the moment when the patch fails it just... fails miserably but doesn't tell you much about why and where.

See the current state of the docs here: 
bdk-android: https://thunderbiscuit.github.io/bdk-android-api-docs/
bdk-jvm: https://thunderbiscuit.github.io/bdk-jvm-api-docs/

Honestly they look pretty good! The question is whether changes will always completely break them or if the process can be streamlined well.

**Comment by thunderbiscuit** [comment]
My tests have been successful, and I was able to apply the patch I had created for `v0.3.2` to the new bindings file generated for `v0.4.0`. Not perfect (2 out of the 16 chunks could not be applied), but it was easy to fix them up manually. My process at this point is the following:

## 1. Generate the bindings file without any docs
cd bdk-ffi
cd bdk-ffi && uniffi-bindgen generate src/bdk.udl --no-format --out-dir ../jvm/src/main/kotlin --language kotlin && cd ..

## 2. Apply the patch
patch --dry-run --fuzz=7 jvm/src/main/kotlin/org/bitcoindevkit/bdk.kt docs.patch
patch --fuzz=10 jvm/src/main/kotlin/org/bitcoindevkit/bdk.kt docs.patch

## 3. Fix manually if anything could not be applied using the patch

## 4. Create new patch using the difference between the pure file and the new documented file
diff bdk.kt bdkwithdocs.kt --contex=70 > docs.patch

## 5. Generate the API docs website
./gradlew :jvm:dokkaHtml

## 6. Publish the website
cd ./jvm/build/dokka/html/
git init .
git add .
git commit -m "Release docs for v0.4.0"
git remote add origin https://github.com/thunderbiscuit/bdk-android-api-docs.git
git push origin master

**Comment by thunderbiscuit** [comment]
I gave the docs for `0.4.0` for both bdk-jvm and bdk-android each a place to live (currently just their own repo so they can publish for free on github pages). This allows us to at least host them and test them while the library evolves. If everything goes well maybe we could buy domain names, but for now this is all right I think.

bdk-android: https://thunderbiscuit.github.io/bdk-android-api-docs/
bdk-jvm: https://thunderbiscuit.github.io/bdk-jvm-api-docs/

**Comment by notmandatory** [comment]
I'm updating the docs for #40 and found this nifty feature in IntelliJ:
https://www.jetbrains.com/help/idea/using-patches.html

I had to manually select the "base" file to be the current `bdk.kt` file and then it worked like a charm.

**Comment by notmandatory** [comment]
When using diff should include the `diff -Z` option to ignore white spaces.

**Comment by notmandatory** [comment]
fixed by #31
