### ISSUE TITLE
Make signature optional for local maven publishing

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-kotlin#21]
I think forcing contributors to set up gpg signatures to simply test/deploy the library locally might be an unnecessary friction we could easily remove.

**Comment by thunderbiscuit** [comment]
Potential avenues for doing this [explained here](https://docs.gradle.org/current/userguide/signing_plugin.html#sec:conditional_signing).

One example they have is where you skip the signing if the artifact name ends with `SNAPSHOT` _and_ you don't have credentials configured. Maybe better IMO would be to skip signature _if_ you don't have credentials set up _and_ you're running the `publishToMavenLocal` task.

**Comment by thunderbiscuit** [comment]
For now even easier (and maybe fine to simply add this to the readme instead?) is to simply exclude the `signMavenPublication` task when publishing to Maven Local using the following line:

```sh
./gradlew :jvm:publishToMavenLocal -x signMavenPublication
```

**Comment by thunderbiscuit** [comment]
I think the above might be the better choice, as it keeps the default to be signatures on everything, and not signing has to be a deliberate choice. Happy to add the fix for the "not signing on `SNAPSHOT`" idea as well if others see value in that more than the command line approach.

**Comment by notmandatory** [comment]
I think updating the README local publishing section is the right way to go; ie remove the current step 1 and add the exclude to remaining step. It leave signing the default but makes it easy to opt out of for testing.
