### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-kotlin#29]
Keeping a changelog is a good practice and all other bdk projects have one. We should add one to bdk-kotlin as well.

Question: do we want one for each of the library or one for both?

**Comment by notmandatory** [comment]
I'm working on a new idea for managing changelog info for `bdk` which should work for all our projects. The basic idea is to keep that info attached in the message body attached to git tags, and not in a single text file. This is what the `tokio` project does and I think it will greatly simplify the PR and release process. Once I get my ideas put together I'll link to the PR here.
