### ISSUE TITLE
Publish sources and javadoc for bdk-android

### ISSUE THREAD

**Issue by kirillzh** [bitcoindevkit/bdk-kotlin#32]
### Problem

It seems that sources and javadocs for bdk-android are not being generated and published to maven:
https://repo1.maven.org/maven2/org/bitcoindevkit/bdk-android/0.4.0.

### Description

When using bdk-android as a library in your project it's not currently possible to look up source code and documentation of bdk-android because sources and javadocs are not being generated and published.

With AGP 7.1.0 publishing Android sources and javadocs is very simple, we can use that https://developer.android.com/studio/releases/gradle-plugin#build-variant-publishing.

**Comment by notmandatory** [comment]
Since the Kotlin code for this project is auto generated by `uniffi-rs` and that project isn't currently able to take docs from the original rust project and translate them into the generated native languages docs.  But @thunderbiscuit has #31 to semi-automate keeping the Kotlin docs up-to-date. Once this goes in our current publish task should publish them to maven central.

**Comment by kirillzh** [comment]
> Once this goes in our current publish task should publish them to maven central.

It looks like only `bdk-jvm` artifact is configured to publish sources and javadoc right now, not the `bdk-android` so that still needs to be configured: https://github.com/bitcoindevkit/bdk-kotlin/pull/33. But I guess since Dokka (yay!) is going to be used instead of javadoc we probably cannot use `withJavadocJar()` that comes with `maven-publish` in AGP 7.1.0 and might need to write custom task to pull out dokka docs as its own artifact (which is easy): https://github.com/Kotlin/dokka/issues/42.

**Comment by thunderbiscuit** [comment]
@kirillzh if you have experience building those types of docs I'd love to discuss more with you! My current process works but is not... ideal (described in #18), and I wonder if I could optimize it, or even automate it (I don't have high hopes for full automation at the moment, but you never know).

**Comment by thunderbiscuit** [comment]
I'm playing around with the answers proposed in [in your link above](https://github.com/Kotlin/dokka/issues/42) but so far unable to replace the javadoc jar with the dokka docs.

**Comment by kirillzh** [comment]
> The build script is unable to find the task task javadocJar in the :android project

Right, that's because maven publish plugin in AGP pre-7.1.0 does not know how to work with javadocs, https://github.com/bitcoindevkit/bdk-kotlin/pull/33 should fix that. I unfortunately don't have a ton of experience setting up dokka... Your custom task looks right but I wonder if it should depend on `dokkaJavadoc` task directly to ensure that `$buildDir/dokka/html` exists? Unsure if that's the problem but wondering if this version works (assuming https://github.com/bitcoindevkit/bdk-kotlin/pull/33 is applied)?

```kotlin
val javadocJar = tasks.named<Jar>("javadocJar") {
  archiveClassifier.set("javadoc")
  from(tasks.named("dokkaJavadoc"))
}
```

**Comment by thunderbiscuit** [comment]
Yeah no that was me testing your PR #33 actually! That's why I was a bit puzzled by it. You bumped AGP to `7.1.2` and it's still not finding it. 

When I print the list of tasks available under `:android` I see `javaDocReleaseJar` (don't remember that one, but I think it is definitely added by the plugin), but even that doesn't get found when I search by name using the `tasks.named()`, so not sure what is going on there.

**Comment by kirillzh** [comment]
> When I print the list of tasks available under `:android` I see `javaDocReleaseJar`

@thunderbiscuit, I think this is because publishing is only configured for release build variant:

```kotlin
publishing {
    singleVariant("release") {
        withSourcesJar()
        withJavadocJar()
    }
}
```
If we want to configure it for all variants we can do it like so:

```kotlin
publishing {
    multipleVariants {
        withSourcesJar()
        withJavadocJar()
        allVariants()
    }
}
```

```bash
$ ./gradlew tasks --all
...
android:javaDocDebugGeneration
android:javaDocDebugJar
android:javaDocReleaseGeneration
android:javaDocReleaseJar
...
```

When I ran `./gradlew :android:publishToMavenLocal -x signMavenPublication` locally I see it correctly generating and publishing sources and javadoc in my local maven, so I wonder if `signMavenPublication` is somehow set up to work in `release` variant. 🤔

**Comment by kirillzh** [comment]
Also, I just tried generating local bdk-kotlin and applying docs with dokka on https://github.com/bitcoindevkit/bdk-kotlin/issues/18 branch + this changes from this PR and I see documentation as part of aar now which is amazing!

On high level, this is what it looks like when I jump to BDK definitions (e.g.`BitcoinTime`) from https://github.com/thunderbiscuit/devkit-wallet repo:
<img width="767" alt="Screen Shot 2022-03-23 at 6 02 06 PM" src="https://user-images.githubusercontent.com/5660531/159821370-bbb31a46-5138-46ff-beae-21a342a65fc6.png">
