### ISSUE TITLE
Migrate build script logic into Gradle plugin

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-kotlin#36]
I have a MVP for a small Gradle plugin that would add the required tasks to build the native libraries and the bindings files, and would love some feedback on the approach. See PR #37.

One of the problems we currently have is that we build the bindings file independently of the native libraries, which creates problems if the version of the uniffi-bindgen cli tool used is not the same as the uniffi-crate dependency.

My current fix for that is to, as part of the plugin, pull the uniffi-rs repo at a specific tag and build the bindgen tool, which can be then used to generate the bindings. This is a bit of extra work because it requires a complete clone and build of the tool, but ensures that every build of the library will be consistent. The version of the cli tool is simply added as a config in the `gradle.properties`; this way we can simply keep both the `Cargo.toml` file and the `gradle.properties` files in sync and ensure the native libs and the bindings are built using the same version of `uniffi-rs`.

**Comment by notmandatory** [comment]
Fixed by #37
