### ISSUE TITLE
Add message signing

### ISSUE THREAD

**Issue by filiplipa** [bitcoindevkit/bdk-kotlin#39]
### Problem

It seems that message signing hasn't been exposed yet in Kotlin.

### Description

It would be useful to have this option to sign messages using private keys.

**Comment by notmandatory** [comment]
Are you looking to sign an arbitrary text message with some private key from your wallet descriptor? and then you'll also need a way to verify the signature with the corresponding public key right? I don't think we have any example for how to do this with `bdk`, but t should be possible though using the `keys` module. 

If anyone wants to write up a an example in Rust for how to sign messages with a `DescriptorSecretKey` and verify them with a `DescriptorPublicKey` that would be helpful.

**Comment by q-src** [comment]
Please see also https://github.com/bitcoindevkit/bdk-ffi/pull/139

**Comment by thunderbiscuit** [comment]
Related to bitcoindevkit/bdk#601. Once the feature is available in Rust BDK we'll expose it to the bindings.
