### ISSUE TITLE
Hosting location of API docs

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-kotlin#46]
Just opening this so we don't forget to migrate the API docs from where they are now (in my private repos) to where they should live long-term.

**Comment by thunderbiscuit** [comment]
PR bitcoindevkit/bitcoindevkit.org#96 fixes this.

**Comment by notmandatory** [comment]
https://github.com/bitcoindevkit/bitcoindevkit.org/pull/96 is merged.
