### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-kotlin#71]
The example in the readme is outdated and should be updated to work with `v0.8.0`.

**Comment by KaiWitt** [comment]
And the linked section in `How to build` >  ["Getting Started (Developer)"](https://github.com/bitcoindevkit/bdk-ffi#getting-started-developer)  doesn't exist anymore

**Comment by thunderbiscuit** [comment]
I don't remember exactly what was in that section. Did it have particular things you wanted to add to the readme? I'm happy to add documentation if there are things you think we should add or clarify.

**Comment by thunderbiscuit** [comment]
This issue has gone stale so I'm going to close it, but feel free to reopen if you have something else you'd like to add to the readme!
