### ISSUE TITLE
Add PGP key to repo and add docs on how to verify signature on libraries

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-kotlin#85]
Title says it all.

**Comment by thunderbiscuit** [comment]
Potential avenue for doing this: https://github.com/ACINQ/eclair

**Comment by notmandatory** [comment]
I think the purpose of the eclair `SECURITY.md` file is so anyone who wants to report a security vulnerability can send an encrypted email or message to the core devs using their public GPG keys. But I also think we can use it for publishing the fingerprint and instructions for the signed kotlin artifacts.
